language: python
python:
- '3.7'
node_js:
- '10'
script:
- |
    npm install
    npm run build
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
