name: Format
on:
  pull_request:
    branches:
      - master

jobs:
  format:
    name: Format and Commit to PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set-up Node
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: npm install
        run: |
          npm install
      - name: npm format
        run: |
          npm run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Format code"
          branch: ${{ github.head_ref }}
