name: PR Build
on:
  pull_request:
    branches:
      - master

jobs:
  build-deploy-gh-pages:
    name: Build / Deploy to gh-pages and Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: npm install
        run: |
          npm install
      - name: npm build frontend
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}